version: '3.7'
services:
  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - django_static:/app/static
      - .:/app
    ports:
      - 8000:8000
    networks:
      - default

volumes:
  django_static:

