version: '3.7'
services:
  app:
    build: .
    command: gunicorn voctoconf.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - django_static:/app/static
      - ./_db.sqlite3:/app/_db.sqlite3
    labels:
      traefik.enable: "true"
      traefik.docker.network: "web"
      traefik.http.routers.voctoconf.rule: "Host(`virtual.piandmore.de`)"
      traefik.http.routers.voctoconf.entrypoints: "web"
      traefik.http.routers.voctoconf.middlewares: "redirect-to-https@file, add-sts-with-subdomains@file"
      traefik.http.routers.voctoconfsecure.rule: "Host(`virtual.piandmore.de`)"
      traefik.http.routers.voctoconfsecure.tls.certresolver: "le"
      traefik.http.routers.voctoconfsecure.entrypoints: "websecure"
      traefik.http.routers.voctoconfsecure.middlewares: "add-sts-with-subdomains@file"
    networks:
      - default
      - redis
      - web
    environment:
      DJANGO_MANAGEPY_MIGRATE: "on"
      DJANGO_MANAGEPY_COLLECTSTATIC: "on"
  redis:
    image: redis:latest
    restart: always
    networks:
      - redis
    labels:
      com.centurylinklabs.watchtower.enable: "true"
  nginx:
    image: nginx:stable-alpine
    volumes:
      - django_static:/app/static
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - default
      - web
    labels:
      traefik.enable: "true"
      traefik.docker.network: "web"
      traefik.http.routers.voctoconfstatic.rule: "Host(`virtual.piandmore.de`) && PathPrefix(`/static`)"
      traefik.http.routers.voctoconfstatic.entrypoints: "web"
      traefik.http.routers.voctoconfstatic.middlewares: "redirect-to-https@file, add-sts-with-subdomains@file"
      traefik.http.routers.voctoconfstaticsecure.rule: "Host(`virtual.piandmore.de`) && PathPrefix(`/static`)"
      traefik.http.routers.voctoconfstaticsecure.tls.certresolver: "le"
      traefik.http.routers.voctoconfstaticsecure.entrypoints: "websecure"
      traefik.http.routers.voctoconfstaticsecure.middlewares: "add-sts-with-subdomains@file"

volumes:
  django_static:

networks:
  default:
  redis:
  web:
    external:
      name: web
