# Generated by Django 3.1.5 on 2021-01-15 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbb', '0012_room_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='auto_join_audio',
            field=models.BooleanField(default=False, verbose_name='Auto Join Audio'),
        ),
        migrations.AddField(
            model_name='room',
            name='auto_share_webcam',
            field=models.BooleanField(default=False, verbose_name='Auto Share Webcam'),
        ),
        migrations.AddField(
            model_name='room',
            name='hide_presentation',
            field=models.BooleanField(default=False, verbose_name='Hide Presentation'),
        ),
        migrations.AddField(
            model_name='room',
            name='skip_echo_test',
            field=models.BooleanField(default=False, verbose_name='Skip Echo Test'),
        ),
    ]
