# Generated by Django 3.1.5 on 2021-01-15 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbb', '0013_auto_20210115_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='auto_join_audio',
        ),
    ]
