# Generated by Django 3.1.5 on 2021-01-15 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbb', '0014_remove_room_auto_join_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='listen_only_mode',
            field=models.BooleanField(default=True, verbose_name='Allow users to join in listen-only mode'),
        ),
    ]
