# Generated by Django 3.1.5 on 2021-01-15 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbb', '0015_room_listen_only_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='auto_swap_layout',
            field=models.BooleanField(default=False, verbose_name='Start with presentation area minimized'),
        ),
        migrations.AddField(
            model_name='room',
            name='show_participants_on_login',
            field=models.BooleanField(default=True, verbose_name='Start with participants panel expanded'),
        ),
        migrations.AddField(
            model_name='room',
            name='show_public_chat_on_login',
            field=models.BooleanField(default=True, verbose_name='Start with chat panel expanded'),
        ),
    ]
